// Generated by scripts/gen_log_file_ids.py. DO NOT EDIT MANUALLY.

#include "obc_log_file_ids.h"

const char *const LOG_FILE_PATHS[LOG_FILE_ID_COUNT] = {
    "obc/app/drivers/arducam/arducam.c",                            // 0
    "obc/app/drivers/arducam/ov5642.c",                             // 1
    "obc/app/drivers/bd621x/bd621x.c",                              // 2
    "obc/app/drivers/cc1120/cc1120.c",                              // 3
    "obc/app/drivers/cc1120/cc1120_mcu.c",                          // 4
    "obc/app/drivers/ds3232/ds3232_mz.c",                           // 5
    "obc/app/drivers/fram/fm25v20a.c",                              // 6
    "obc/app/drivers/lm75bd/lm75bd.c",                              // 7
    "obc/app/drivers/max5360/max5360.c",                            // 8
    "obc/app/drivers/rffm6404/rffm6404.c",                          // 9
    "obc/app/drivers/rm46/obc_adc.c",                               // 10
    "obc/app/drivers/rm46/obc_exception_handlers.c",                // 11
    "obc/app/drivers/rm46/obc_i2c_io.c",                            // 12
    "obc/app/drivers/rm46/obc_spi_dma.c",                           // 13
    "obc/app/drivers/rm46/obc_spi_io.c",                            // 14
    "obc/app/drivers/rm46/obc_spi_io.h",                            // 15
    "obc/app/drivers/sdcard/sdc_bdev.c",                            // 16
    "obc/app/drivers/vn100/vn100.c",                                // 17
    "obc/app/modules/alarm_mgr/alarm_handler.c",                    // 18
    "obc/app/modules/camera_mgr/camera_control.c",                  // 19
    "obc/app/modules/command_mgr/command_callbacks.c",              // 20
    "obc/app/modules/command_mgr/command_manager.c",                // 21
    "obc/app/modules/comms_link_mgr/cc1120_txrx.c",                 // 22
    "obc/app/modules/comms_link_mgr/comms_manager.c",               // 23
    "obc/app/modules/comms_link_mgr/downlink_encoder.c",            // 24
    "obc/app/modules/comms_link_mgr/uplink_decoder.c",              // 25
    "obc/app/modules/digital_watchdog_mgr/digital_watchdog_mgr.c",  // 26
    "obc/app/modules/gnc_mgr/gnc_manager.c",                        // 27
    "obc/app/modules/health_collector/health_collector.c",          // 28
    "obc/app/modules/logger/logger.c",                              // 29
    "obc/app/modules/state_mgr/state_mgr.c",                        // 30
    "obc/app/modules/task_stats_collector/task_stats_collector.c",  // 31
    "obc/app/modules/telemetry_mgr/telemetry_fs_utils.c",           // 32
    "obc/app/modules/telemetry_mgr/telemetry_manager.c",            // 33
    "obc/app/modules/timekeeper/timekeeper.c",                      // 34
    "obc/app/sys/fs_wrapper/obc_reliance_fs.c",                     // 35
    "obc/app/sys/persistent/obc_persistent.c",                      // 36
    "obc/app/sys/print/obc_print.c",                                // 37
    "obc/app/sys/time/obc_time.c",                                  // 38
    "obc/bl/bl_main.c",                                             // 39
    "obc/examples/test_app_arducam/main.c",                         // 40
    "obc/examples/test_app_cc1120_spi/cc1120_spi_tests.c",          // 41
    "obc/examples/test_app_rtc/main.c",                             // 42
    "obc/shared/commands/command.c",                                // 43
    "obc/shared/logging/obc_logging.h",                             // 44
};
