#pragma once

// Generated by scripts/gen_log_file_ids.py. DO NOT EDIT MANUALLY.

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define LOG_FILE_ID_COUNT 45U

// Repo-relative paths of all files that use the logging macros,
// sorted alphabetically. A file's ID is its index in this table.
extern const char *const LOG_FILE_PATHS[LOG_FILE_ID_COUNT];

#ifdef __cplusplus
}
#endif
