#pragma once

typedef enum {
  /* Logging errors 0 - 49 */
  GS_ERR_CODE_SUCCESS = 0,
  GS_ERR_CODE_INVALID_ARG = 1,
  GS_ERR_CODE_BUFF_TOO_SMALL = 2,
  GS_ERR_CODE_LOG_MSG_SILENCED = 3,
  GS_ERR_CODE_FAILED_FILE_OPEN = 10,
  GS_ERR_CODE_FAILED_FILE_CLOSE = 11,
  GS_ERR_CODE_FAILED_FILE_WRITE = 12,
  GS_ERR_CODE_MKDIR_FAILED = 13,

  /* Common errors 50 - 99 */
  GS_ERR_CODE_CORRUPTED_MSG = 50,
  GS_ERR_CODE_AX25_DECODE_FAILURE = 51,

} gs_error_code_t;
