/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_RECTANGLE_H
#define _MOCK_RECTANGLE_H

#include "unity.h"
#include "rectangle.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void mock_rectangle_Init(void);
void mock_rectangle_Destroy(void);
void mock_rectangle_Verify(void);




#define rectangle_init_Expect(length, width) rectangle_init_CMockExpect(__LINE__, length, width)
void rectangle_init_CMockExpect(UNITY_LINE_TYPE cmock_line, uint16_t length, uint16_t width);
#define rectangle_get_area_ExpectAndReturn(cmock_retval) rectangle_get_area_CMockExpectAndReturn(__LINE__, cmock_retval)
void rectangle_get_area_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return);
#define rectangle_get_perimeter_ExpectAndReturn(cmock_retval) rectangle_get_perimeter_CMockExpectAndReturn(__LINE__, cmock_retval)
void rectangle_get_perimeter_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return);
#define rectangle_is_square_ExpectAndReturn(cmock_retval) rectangle_is_square_CMockExpectAndReturn(__LINE__, cmock_retval)
void rectangle_is_square_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return);

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
