/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_rectangle.h"

static const char* CMockString_length = "length";
static const char* CMockString_rectangle_get_area = "rectangle_get_area";
static const char* CMockString_rectangle_get_perimeter = "rectangle_get_perimeter";
static const char* CMockString_rectangle_init = "rectangle_init";
static const char* CMockString_rectangle_is_square = "rectangle_is_square";
static const char* CMockString_width = "width";

typedef struct _CMOCK_rectangle_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint16_t Expected_length;
  uint16_t Expected_width;

} CMOCK_rectangle_init_CALL_INSTANCE;

typedef struct _CMOCK_rectangle_get_area_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint16_t ReturnVal;

} CMOCK_rectangle_get_area_CALL_INSTANCE;

typedef struct _CMOCK_rectangle_get_perimeter_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint16_t ReturnVal;

} CMOCK_rectangle_get_perimeter_CALL_INSTANCE;

typedef struct _CMOCK_rectangle_is_square_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  bool ReturnVal;

} CMOCK_rectangle_is_square_CALL_INSTANCE;

static struct mock_rectangleInstance
{
  CMOCK_MEM_INDEX_TYPE rectangle_init_CallInstance;
  CMOCK_MEM_INDEX_TYPE rectangle_get_area_CallInstance;
  CMOCK_MEM_INDEX_TYPE rectangle_get_perimeter_CallInstance;
  CMOCK_MEM_INDEX_TYPE rectangle_is_square_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void mock_rectangle_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.rectangle_init_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_rectangle_init);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.rectangle_get_area_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_rectangle_get_area);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.rectangle_get_perimeter_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_rectangle_get_perimeter);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.rectangle_is_square_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_rectangle_is_square);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void mock_rectangle_Init(void)
{
  mock_rectangle_Destroy();
}

void mock_rectangle_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void rectangle_init(uint16_t length, uint16_t width)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_rectangle_init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_rectangle_init);
  cmock_call_instance = (CMOCK_rectangle_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.rectangle_init_CallInstance);
  Mock.rectangle_init_CallInstance = CMock_Guts_MemNext(Mock.rectangle_init_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_rectangle_init,CMockString_length);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_length, length, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_rectangle_init,CMockString_width);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_width, width, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_rectangle_init(CMOCK_rectangle_init_CALL_INSTANCE* cmock_call_instance, uint16_t length, uint16_t width);
void CMockExpectParameters_rectangle_init(CMOCK_rectangle_init_CALL_INSTANCE* cmock_call_instance, uint16_t length, uint16_t width)
{
  cmock_call_instance->Expected_length = length;
  cmock_call_instance->Expected_width = width;
}

void rectangle_init_CMockExpect(UNITY_LINE_TYPE cmock_line, uint16_t length, uint16_t width)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rectangle_init_CALL_INSTANCE));
  CMOCK_rectangle_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_rectangle_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rectangle_init_CallInstance = CMock_Guts_MemChain(Mock.rectangle_init_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_rectangle_init(cmock_call_instance, length, width);
}

uint16_t rectangle_get_area(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_rectangle_get_area_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_rectangle_get_area);
  cmock_call_instance = (CMOCK_rectangle_get_area_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.rectangle_get_area_CallInstance);
  Mock.rectangle_get_area_CallInstance = CMock_Guts_MemNext(Mock.rectangle_get_area_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void rectangle_get_area_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rectangle_get_area_CALL_INSTANCE));
  CMOCK_rectangle_get_area_CALL_INSTANCE* cmock_call_instance = (CMOCK_rectangle_get_area_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rectangle_get_area_CallInstance = CMock_Guts_MemChain(Mock.rectangle_get_area_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

uint16_t rectangle_get_perimeter(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_rectangle_get_perimeter_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_rectangle_get_perimeter);
  cmock_call_instance = (CMOCK_rectangle_get_perimeter_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.rectangle_get_perimeter_CallInstance);
  Mock.rectangle_get_perimeter_CallInstance = CMock_Guts_MemNext(Mock.rectangle_get_perimeter_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void rectangle_get_perimeter_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rectangle_get_perimeter_CALL_INSTANCE));
  CMOCK_rectangle_get_perimeter_CALL_INSTANCE* cmock_call_instance = (CMOCK_rectangle_get_perimeter_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rectangle_get_perimeter_CallInstance = CMock_Guts_MemChain(Mock.rectangle_get_perimeter_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

bool rectangle_is_square(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_rectangle_is_square_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_rectangle_is_square);
  cmock_call_instance = (CMOCK_rectangle_is_square_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.rectangle_is_square_CallInstance);
  Mock.rectangle_is_square_CallInstance = CMock_Guts_MemNext(Mock.rectangle_is_square_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void rectangle_is_square_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rectangle_is_square_CALL_INSTANCE));
  CMOCK_rectangle_is_square_CALL_INSTANCE* cmock_call_instance = (CMOCK_rectangle_is_square_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rectangle_is_square_CallInstance = CMock_Guts_MemChain(Mock.rectangle_is_square_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

