# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _obc_gs_errors
else:
    import _obc_gs_errors

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


OBC_GS_ERR_CODE_SUCCESS = _obc_gs_errors.OBC_GS_ERR_CODE_SUCCESS
OBC_GS_ERR_CODE_INVALID_ARG = _obc_gs_errors.OBC_GS_ERR_CODE_INVALID_ARG
OBC_GS_ERR_CODE_BUFF_TOO_SMALL = _obc_gs_errors.OBC_GS_ERR_CODE_BUFF_TOO_SMALL
OBC_GS_ERR_CODE_UNSUPPORTED_CMD = _obc_gs_errors.OBC_GS_ERR_CODE_UNSUPPORTED_CMD
OBC_GS_ERR_CODE_REED_SOL_ENC_ERR = _obc_gs_errors.OBC_GS_ERR_CODE_REED_SOL_ENC_ERR
OBC_GS_ERR_CODE_REED_SOL_DEC_ERR = _obc_gs_errors.OBC_GS_ERR_CODE_REED_SOL_DEC_ERR
OBC_GS_ERR_CODE_INVALID_AX25_PACKET = _obc_gs_errors.OBC_GS_ERR_CODE_INVALID_AX25_PACKET
OBC_GS_ERR_CODE_CORRUPTED_AX25_MSG = _obc_gs_errors.OBC_GS_ERR_CODE_CORRUPTED_AX25_MSG
OBC_GS_ERR_CODE_INVALID_TNC = _obc_gs_errors.OBC_GS_ERR_CODE_INVALID_TNC


