# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _obc_gs_aes128
else:
    import _obc_gs_aes128

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


AES_BLOCK_SIZE = _obc_gs_aes128.AES_BLOCK_SIZE
AES_KEY_SIZE = _obc_gs_aes128.AES_KEY_SIZE
AES_IV_SIZE = _obc_gs_aes128.AES_IV_SIZE
class aes_data_t(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    iv = property(_obc_gs_aes128.aes_data_t_iv_get, _obc_gs_aes128.aes_data_t_iv_set)
    ciphertext = property(_obc_gs_aes128.aes_data_t_ciphertext_get, _obc_gs_aes128.aes_data_t_ciphertext_set)
    ciphertextLen = property(_obc_gs_aes128.aes_data_t_ciphertextLen_get, _obc_gs_aes128.aes_data_t_ciphertextLen_set)

    def __init__(self):
        _obc_gs_aes128.aes_data_t_swiginit(self, _obc_gs_aes128.new_aes_data_t())
    __swig_destroy__ = _obc_gs_aes128.delete_aes_data_t

# Register aes_data_t in _obc_gs_aes128:
_obc_gs_aes128.aes_data_t_swigregister(aes_data_t)


def aes128Decrypt(aesData, output, outputBufferLen):
    return _obc_gs_aes128.aes128Decrypt(aesData, output, outputBufferLen)

def initializeAesCtx(key):
    return _obc_gs_aes128.initializeAesCtx(key)


