#ifndef COMMON_INCLUDE_OBC_ERRORS_H_
#define COMMON_INCLUDE_OBC_ERRORS_H_

typedef enum {
    /* Common Errors 0 - 99 */
    OBC_ERR_CODE_SUCCESS = 0,
    OBC_ERR_CODE_UNKNOWN,
    OBC_ERR_CODE_INVALID_ARG,
    OBC_ERR_CODE_QUEUE_FULL,
    OBC_ERR_CODE_MUTEX_TIMEOUT,
    OBC_ERR_CODE_BUFF_TOO_SMALL,
    OBC_ERR_CODE_LOG_MSG_SILENCED,
    OBC_ERR_CODE_INVALID_STATE,
    OBC_ERR_CODE_UNSUPPORTED_EVENT,

    /* Driver Errors 100 - 199*/
    OBC_ERR_CODE_SPI_FAILURE = 100,
    OBC_ERR_CODE_I2C_FAILURE,
    OBC_ERR_CODE_UART_FAILURE,

    /* CDH errors 200 - 299 */    


    /* ADCS errors 300 - 399 */


    /* EPS errors 400 - 499 */


    /* COMMS errors 500 - 599 */


    /* Payload errors 600 - 699 */

    /* File System errors 700 - 799 */
    OBC_ERR_CODE_INVALID_FILE_NAME = 700,
    OBC_ERR_CODE_FAILED_FILE_OPEN,
    OBC_ERR_CODE_FAILED_FILE_CLOSE,
    OBC_ERR_CODE_FAILED_FILE_WRITE,
    OBC_ERR_CODE_FAILED_FILE_READ,
    OBC_ERR_CODE_REACHED_EOF,


} obc_error_code_t;


#endif // COMMON_INCLUDE_OBC_ERRORS_H_