cmake_minimum_required(VERSION 3.15)

if (${BOARD_TYPE} MATCHES RM46_LAUNCHPAD)
    set(COMMON_LIB rm46-launchpad-common)
elseif(${BOARD_TYPE} MATCHES OBC_REVISION_1)
    set(COMMON_LIB obc-rev1-common)
elseif(${BOARD_TYPE} MATCHES OBC_REVISION_2)
    set(COMMON_LIB obc-rev2-common)
else()
    message(FATAL_ERROR "Invalid board type: ${BOARD_TYPE}")
endif()

set(HAL_LIB_OPTIMIZE ${COMMON_LIB}-optimize)
set(HAL_LIB_NO_OPTIMIZE ${COMMON_LIB}-no-optimize)
set(FREERTOS_LIB_OPTIMIZE ${COMMON_LIB}-freertos-optimize)
set(FREERTOS_LIB_NO_OPTIMIZE ${COMMON_LIB}-freertos-no-optimize)