#define DMA_PORT_B 0x04

// DMA SPI channels
#define DMA_SPI_1_RX_CHANNEL DMA_CH0
#define DMA_SPI_1_TX_CHANNEL DMA_CH1
#define DMA_SPI_3_RX_CHANNEL DMA_CH2
#define DMA_SPI_3_TX_CHANNEL DMA_CH3

// DMA request lines
#define DMA_SPI1_RX_REQ_LINE 0
#define DMA_SPI1_TX_REQ_LINE 1
#define DMA_SPI3_RX_REQ_LINE 14
#define DMA_SPI3_TX_REQ_LINE 15
