"""
create callsign table

Revision ID: ee5986331915
Revises: eb50ffe96509
Create Date: 2025-11-22 17:48:07.964708

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "ee5986331915"
down_revision = "eb50ffe96509"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """ """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "callsigns",
        sa.Column("call_sign", sqlmodel.sql.sqltypes.AutoString(length=6), nullable=False),
        sa.Column("first_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("last_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("personal_address", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("personal_city", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("personal_province", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("personal_postal_code", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("qual_level_a", sa.Boolean(), nullable=False),
        sa.Column("qual_level_b", sa.Boolean(), nullable=False),
        sa.Column("qual_level_c", sa.Boolean(), nullable=False),
        sa.Column("qual_level_d", sa.Boolean(), nullable=False),
        sa.Column("qual_level_e", sa.Boolean(), nullable=False),
        sa.Column("club_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("second_club_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("club_address", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("club_city", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("club_province", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("club_postal_code", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.PrimaryKeyConstraint("call_sign"),
        schema="aro_users",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """ """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("callsigns", schema="aro_users")
    # ### end Alembic commands ###
