# board_config_definitions.cmake

if(BOARD_TYPE STREQUAL "RM46_LAUNCHPAD")
    # No macros defined for RM46_LAUNCHPAD
elseif(BOARD_TYPE STREQUAL "OBC_REVISION_1")
    set(PERIPHERAL_CONFIG -DCONFIG_DS3232 -DCONFIG_SD_CARD -DCONFIG_FRAM -DCONFIG_LM75BD)
elseif(BOARD_TYPE STREQUAL "OBC_REVISION_2")
    set(PERIPHERAL_CONFIG -DCONFIG_DS3232 -DCONFIG_SD_CARD -DCONFIG_FRAM -DCONFIG_LM75BD -DCONFIG_TPL5010)
else()
    message(FATAL_ERROR "Invalid BOARD_TYPE: ${BOARD_TYPE}. Board config not defined")
endif()
