#!/usr/bin/env python3
"""Generate the log file ID table used by the compact binary log format.

Scans the firmware sources for files that use the logging macros and assigns
each one a stable ID (its index in the alphabetically sorted path list).

Outputs (all checked into the repo):
  - obc/shared/logging/obc_log_file_ids.h   (C declarations)
  - obc/shared/logging/obc_log_file_ids.c   (C path table)
  - obc/shared/logging/log_file_ids.json    (mapping for the ground station)

The JSON file must be copied to the ground-station repo
(backend/obc_utils/log_file_ids.json) whenever it changes, so the ground
station can decode file IDs back into file paths.

Usage:
  python3 scripts/gen_log_file_ids.py           # regenerate the tables
  python3 scripts/gen_log_file_ids.py --check   # exit non-zero if tables are stale (for CI)
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

# Directories containing code that can run on the OBC and produce logs
SCAN_DIRS = ["obc", "interfaces"]

SOURCE_SUFFIXES = {".c", ".h"}

# Any invocation of a logging macro (LOG_INFO(...), LOG_ERROR_CODE(...),
# RETURN_IF_ERROR_CODE(...), etc.)
LOG_MACRO_RE = re.compile(
    r"\b(LOG_(?:TRACE|DEBUG|INFO|WARN|ERROR|FATAL)(?:_FROM_ISR)?"
    r"|LOG_ERROR_CODE(?:_FROM_ISR)?"
    r"|LOG_IF_ERROR_CODE"
    r"|RETURN_IF_ERROR_CODE"
    r"|RETURN_AND_GIVE_IF_ERROR_CODE)\s*\("
)

OUT_DIR = REPO_ROOT / "obc" / "shared" / "logging"
HEADER_PATH = OUT_DIR / "obc_log_file_ids.h"
SOURCE_PATH = OUT_DIR / "obc_log_file_ids.c"
JSON_PATH = OUT_DIR / "log_file_ids.json"

GENERATED_NOTICE = "Generated by scripts/gen_log_file_ids.py. DO NOT EDIT MANUALLY."


def find_logging_files() -> list[str]:
    paths: set[str] = set()
    for scan_dir in SCAN_DIRS:
        for path in (REPO_ROOT / scan_dir).rglob("*"):
            if path.suffix not in SOURCE_SUFFIXES or not path.is_file():
                continue
            try:
                content = path.read_text(errors="ignore")
            except OSError:
                continue
            if LOG_MACRO_RE.search(content):
                paths.add(path.relative_to(REPO_ROOT).as_posix())
    return sorted(paths)


def render_header(count: int) -> str:
    return f"""#pragma once

// {GENERATED_NOTICE}

#include <stdint.h>

#ifdef __cplusplus
extern "C" {{
#endif

#define LOG_FILE_ID_COUNT {count}U

// Repo-relative paths of all files that use the logging macros,
// sorted alphabetically. A file's ID is its index in this table.
extern const char *const LOG_FILE_PATHS[LOG_FILE_ID_COUNT];

#ifdef __cplusplus
}}
#endif
"""


def _align_trailing_comments(lines: list[str]) -> list[str]:
    """Align // comments to match clang-format (AlignTrailingComments, SpacesBeforeTrailingComments: 2)."""
    prefixes: list[str] = []
    for line in lines:
        comment_idx = line.index("//")
        prefixes.append(line[:comment_idx].rstrip())

    max_prefix_len = max(len(prefix) for prefix in prefixes)
    aligned: list[str] = []
    for line in lines:
        comment_idx = line.index("//")
        prefix = line[:comment_idx].rstrip()
        comment = line[comment_idx:]
        pad = max_prefix_len - len(prefix) + 2
        aligned.append(f"{prefix}{' ' * pad}{comment}")
    return aligned


def render_source(paths: list[str]) -> str:
    raw_lines = [f'    "{p}",  // {i}' for i, p in enumerate(paths)]
    table = "\n".join(_align_trailing_comments(raw_lines))
    return f"""// {GENERATED_NOTICE}

#include "obc_log_file_ids.h"

const char *const LOG_FILE_PATHS[LOG_FILE_ID_COUNT] = {{
{table}
}};
"""


def render_json(paths: list[str]) -> str:
    return json.dumps({"format_version": 1, "files": paths}, indent=2) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="verify generated files are up to date"
    )
    args = parser.parse_args()

    paths = find_logging_files()
    outputs = {
        HEADER_PATH: render_header(len(paths)),
        SOURCE_PATH: render_source(paths),
        JSON_PATH: render_json(paths),
    }

    if args.check:
        stale = [
            p
            for p, content in outputs.items()
            if not p.exists() or p.read_text() != content
        ]
        if stale:
            for p in stale:
                print(f"STALE: {p.relative_to(REPO_ROOT)}", file=sys.stderr)
            print("Run scripts/gen_log_file_ids.py to regenerate.", file=sys.stderr)
            return 1
        print("Log file ID tables are up to date.")
        return 0

    for path, content in outputs.items():
        path.write_text(content)
        print(f"Wrote {path.relative_to(REPO_ROOT)}")
    print(f"{len(paths)} files in the log file ID table.")
    print(
        "Remember to copy log_file_ids.json to ground-station/backend/obc_utils/ if it changed."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
