from typing import Final

MAX_CMD_MSG_SIZE: Final[int] = 16
MAX_REPONSE_PACKED_SIZE: Final[int] = 16
RS_DECODED_DATA_SIZE: Final[int] = 223
RS_ENCODED_DATA_SIZE: Final[int] = 255
OBC_UART_BAUD_RATE: Final = 115200
INFO_FIELD_START_POSITION: Final[int] = 17
INFO_FIELD_END_POSITION: Final[int] = 271
