#ifndef _DRIVERS_INCLUDE_OBC_WATCHDOG_H_
#define _DRIVERS_INCLUDE_OBC_WATCHDOG_H_

#define DWWD_NAME "Digital Windowed Watchdog"
#define DWWD_STACK_SIZE 60
#define DWWD_PRIORITY 1

#endif //_DRIVERS_INCLUDE_OBC_WATCHDOG_H_