name: build
on: [push, pull_request]
env:
  ARM_NONE_EABI_GCC_PATH: none

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup
      run: |
        sudo apt-get -y install build-essential cmake
        
    - name: Build (Release-Launchpad)
      run: |
        cmake .. -DCMAKE_BUILD_TYPE=Firmware -G"Unix Makefiles" BOARD_TYPE=RM46_LAUNCHPAD
        make

    - name: Build (Release-OBC Rev1)
      run: |
        cmake .. -DCMAKE_BUILD_TYPE=Firmware -G"Unix Makefiles" BOARD_TYPE=OBC_REVISION_1
        make

    - name: Build (Release-OBC Rev2)
      run: |
        cmake .. -DCMAKE_BUILD_TYPE=Firmware -G"Unix Makefiles" BOARD_TYPE=OBC_REVISION_2
        make
