name: Frontend Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: ['aro', 'mcc']

    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Install dependencies for ${{matrix.project}}
        run: |
          cd ./gs/frontend/${{matrix.project}}
          deno install
      - name: Build ${{matrix.project}}
        run: |
          cd ./gs/frontend/${{matrix.project}}
          deno task build
