name: Frontend Build
on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: ['aro', 'mcc']

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies for ${{matrix.project}}
        run: |
          cd ./gs/frontend/${{matrix.project}}
          npm ci
      - name: Build ${{matrix.project}}
        run: |
          cd ./gs/frontend/${{matrix.project}}
          npm run build
