name: HIL Build

on:
  workflow_dispatch:

concurrency:
  group: hil-manual
  cancel-in-progress: true

jobs:
  hil-on-pi:
    runs-on: [self-hosted]

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - name: Install deps on Pi
        run: |
          sudo apt-get update
          sudo apt-get -y install python3-venv build-essential cmake
          python3 -m venv .venv
          source .venv/bin/activate
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt || true
          python3 -m pip install -r obc/tools/python/requirements.txt || true
          python3 -m pip install -e .

      - name: Build GS
        run: |
          cmake -S . -B build_gs -DCMAKE_BUILD_TYPE=GS
          cmake --build build_gs -j

      - name: Build OBC Firmware
        run: |
          cmake -S . -B build_arm -DCMAKE_BUILD_TYPE=OBC -DBOARD_TYPE=OBC_REVISION_1 -DDEBUG=0
          cmake --build build_arm -j

      - name: Flash & Run HIL
        env:
          PORT: /dev/ttyUSB0  # this will be the UART port for pi
        run: |
          source .venv/bin/activate
          python3 obc/tools/python/app_update.py "$PORT" ~/OBC-firmware/build_arm/OBC-firmware.bin
          python3 hil/hil_main.py "$PORT" ~/OBC-firmware/build_arm/OBC-firmware.bin