// The output.log file in this directory was generated by
// the ephemeris.py script. It is a visual display of the
// sunData.bin file
#include "sun_file.h"
#include "ephemeris.h"

#include "obc_errors.h"
#include "obc_print.h"
#include "obc_sci_io.h"
#include "obc_i2c_io.h"
#include "obc_spi_io.h"
#include "sun_utils.h"

#include <FreeRTOS.h>
#include <os_task.h>

#include <sys_common.h>
#include <sys_core.h>
#include <gio.h>
#include <sci.h>
#include <i2c.h>
#include <spi.h>
#include <can.h>
#include <het.h>

#include <string.h>
#include <stdio.h>
static StaticTask_t taskBuffer;
static StackType_t taskStack[2560];

#define STOP_ON_ERROR(text, _ret)                   \
  errCode = _ret;                                   \
  if (errCode != OBC_ERR_CODE_SUCCESS) {            \
    sciPrintf("%s returned %d\r\n", text, errCode); \
    sciPrintf("Stopping example\r\n");              \
    while (1)                                       \
      ;                                             \
  }                                                 \
  sciPrintf("%s was successful\r\n", text)

#define CLEANUP_ON_ERROR(text, _ret, fileName)                \
  errCode = _ret;                                             \
  if (errCode != OBC_ERR_CODE_SUCCESS) {                      \
    sciPrintf("%s failed with error %d\r\n", text, errCode);  \
    deleteFile(fileName);                                     \
    sciPrintf("Deleted file %s\r\n", fileName);               \
    while(1);                                                 \
  }                                                           \
  sciPrintf("%s was successful\r\n", text);                   \

void vTask1(void *pvParameters) {
  // Data from JD1 to JD99 inclusive with step of 1 JD
  const char *fName = "/sunData.bin";

  // Init

  obc_error_code_t errCode;
  STOP_ON_ERROR("sunFileInit", sunFileInit(fName));
  sciPrintf("Sun module successfully initialized");

  // Basic checks

  julian_date_t minJD;
  STOP_ON_ERROR("sunFileGetMinJD", sunFileGetMinJD(&minJD));
  sciPrintf("Minimum JD: %lf\r\n", minJD);

  julian_date_t maxJD;
  STOP_ON_ERROR("sunFileGetMaxJD", sunFileGetMaxJD(&maxJD));
  sciPrintf("Maximum JD: %lf\r\n", maxJD);

  uint32_t number;
  STOP_ON_ERROR("sunFileGetNumDataPoints", sunFileGetNumDataPoints(&number));
  sciPrintf("Number of data points: %d\r\n", number);

  // In Range Check

  bool isInRange = false;
  STOP_ON_ERROR("sunFileJDInRange JD=0.5", sunFileJDInRange(0.5, &isInRange));
  sciPrintf("isInRange: %d\r\n", isInRange);

  STOP_ON_ERROR("sunFileJDInRange JD=1", sunFileJDInRange(1, &isInRange));
  sciPrintf("isInRange: %d\r\n", isInRange);

  STOP_ON_ERROR("sunFileJDInRange JD=8", sunFileJDInRange(8, &isInRange));
  sciPrintf("isInRange: %d\r\n", isInRange);

  STOP_ON_ERROR("sunFileJDInRange JD=99", sunFileJDInRange(99, &isInRange));
  sciPrintf("isInRange: %d\r\n", isInRange);

  STOP_ON_ERROR("sunFileJDInRange JD=100", sunFileJDInRange(100, &isInRange));
  sciPrintf("isInRange: %d\r\n", isInRange);

  STOP_ON_ERROR("sunFileJDInRange JD=2.5", sunFileJDInRange(2.5, &isInRange));
  sciPrintf("isInRange: %d\r\n", isInRange);

  // Get Index of JD:

  uint32_t index;
  STOP_ON_ERROR("sunFileGetIndexOfJD JD=1", sunFileGetIndexOfJD(1, &index));
  sciPrintf("Index of JD=1 %d\r\n", index);

  STOP_ON_ERROR("sunFileGetIndexOfJD JD=33", sunFileGetIndexOfJD(33, &index));
  sciPrintf("Index of JD=33 %d\r\n", index);

  STOP_ON_ERROR("sunFileGetIndexOfJD JD=99", sunFileGetIndexOfJD(99, &index));
  sciPrintf("Index of JD=99 %d\r\n", index);

  // Should round down
  STOP_ON_ERROR("sunFileGetIndexOfJD JD=1.5", sunFileGetIndexOfJD(1.5, &index));
  sciPrintf("Index of JD=1.5 %d\r\n", index);

  STOP_ON_ERROR("sunFileGetIndexOfJD JD=50.4", sunFileGetIndexOfJD(50.4, &index));
  sciPrintf("Index of JD=50.4 %d\r\n", index);

  // Read data point

  position_data_t readData;

  // Stored at index 0:
  position_data_t expected1 = {
      .julianDate = 1, .x = 1.384519786747137E+08, .y = -5.472710939424842E+07, .z = -1.276932755237378E+06};
  STOP_ON_ERROR("sunFileReadDataPoint index=0", sunFileReadDataPoint(0, &readData));
  sciPrintf("Expected %d\r\n", closePositionData(expected1, readData));

  // Stored at index 32:
  position_data_t expected2 = {
      .julianDate = 33.000000000, .x = 1.481637529364224E+08, .y = 2.596441718873117E+07, .z = -5.378180895996094E+04};
  STOP_ON_ERROR("sunFileReadDataPoint index=33", sunFileReadDataPoint(33, &readData));
  sciPrintf("Expected %d\r\n", closePositionData(expected2, readData));

  // Stored at index 98:
  position_data_t expected3 = {
      .julianDate = 99.000000000, .x = 4.391066938786460E+07, .y = 1.459188402378541E+08, .z = 2.131411070142508E+06};
  STOP_ON_ERROR("sunFileReadDataPoint index=98", sunFileReadDataPoint(98, &readData));
  sciPrintf("Expected %d\r\n", closePositionData(expected3, readData));

  /*     Ephemeris test       */

  STOP_ON_ERROR("sunPositionInit", sunPositionInit());
  const char *actualFileName = sunPositionGetFileName();
  sciPrintf("File name: %s", actualFileName);

  // sunPositionGet Basic

  STOP_ON_ERROR("sunPositionGet(1)", sunPositionGet(1, &readData));
  sciPrintf("Expected %d\r\n", closePositionData(expected1, readData));

  STOP_ON_ERROR("sunPositionGet(33)", sunPositionGet(33, &readData));
  sciPrintf("Expected %d\r\n", closePositionData(expected2, readData));

  STOP_ON_ERROR("sunPositionGet(99)", sunPositionGet(99.000000000, &readData));
  sciPrintf("Expected %d\r\n", closePositionData(expected3, readData));

  // Testing linear interpolation
  position_data_t expected4 = {6.9, 39864448.7227, -1415999740.727, 7447.80624892};
  STOP_ON_ERROR("sunPositionGet(6.9)", sunPositionGet(6.9, &readData));
  sciPrintf("Expected %d\r\n", closePositionData(expected4, readData));

  // Get number of data points after specific JD

  uint32_t pointsAfter;
  STOP_ON_ERROR("sunFileGetNumDataPointsAfter JD=50", sunFileGetNumDataPointsAfter(50.0, &pointsAfter));
  sciPrintf("Data points after JD=50: %d\r\n", pointsAfter);

  STOP_ON_ERROR("sunFileGetNumDataPointsAfter JD=70.5", sunFileGetNumDataPointsAfter(70.5, &pointsAfter));
  sciPrintf("Data points after JD=70.5: %d\r\n", pointsAfter);

  STOP_ON_ERROR("sunFileGetNumDataPointsAfter JD=82.77", sunFileGetNumDataPointsAfter(82.77, &pointsAfter));
  sciPrintf("Data points after JD=82.77: %d\r\n", pointsAfter);



  sciPrintf("Test complete");
  while (true) {
  }
}

void runSunPositionTests(){
  sciPrintf("Sun position tests\r\n");
  obc_error_code_t errCode;
  position_data_t testData;

  CLEANUP_ON_ERROR("sunPositionGet(1.0)", sunPositionGet(1.0, &testData), "/sunData.bin");
  sciPrintf("JD=1.0: x=%e, y=%e, z=%e\r\n", testData.x, testData.y, testData.z);
  CLEANUP_ON_ERROR("sunPositionGet(33.0)", sunPositionGet(33.0, &testData), "/sunData.bin");
  sciPrintf("JD=33.0: x=%e, y=%e, z=%e\r\n", testData.x, testData.y, testData.z);

  sciPrintf("Completed sun position tests\r\n");
}

void vTask2(void *pvParameters) {

  // Data from ephemeris.py (8 KB)
  position_data_t ephemerisData[256];
  FILE *inputFile = fopen("sunData.bin", "rb");
  while(inputFile == NULL) {
    sciPrintf("Could not open sunData.bin\r\n");
  }

  // Skip header, then read data points
  fseek(inputFile, 20, SEEK_SET);
  for (int i = 0; i < 255; i++) {
    float x, y, z;
    fread(&x, sizeof(float), 1, inputFile);
    fread(&y, sizeof(float), 1, inputFile);
    fread(&z, sizeof(float), 1, inputFile);
    ephemerisData[i].julianDate = (double)(i + 1);  // Since i starts at 0 and jd starts at 1
    ephemerisData[i].x = (double)x;
    ephemerisData[i].y = (double)y;
    ephemerisData[i].z = (double)z;
  }
  fclose(inputFile);

  // Write data points to new file
  const char *sunFileName = "/sunData.bin";
  int32_t fileID;
  obc_error_code_t errCode;
  STOP_ON_ERROR("createFile", createFile(sunFileName, &fileID));
  STOP_ON_ERROR("sunFileWriteHeader", sunFileWriteHeader(1.0, 1.0, 255));
  for (int i = 0; i < 255; i++) {
    STOP_ON_ERROR("sunFileWriteDataPoint", sunFileWriteDataPoint(i, &ephemerisData[i]));
  }
  STOP_ON_ERROR("closeFile", closeFile(fileID));

  STOP_ON_ERROR("sunPositionInit", sunPositionInit());
  sciPrintf("Sun module initialized\r\n");
  
  // Testing
  runSunPositionTests();
  sciPrintf("Deleting file\r\n");
  deleteFile("/sunData.bin");

  sciPrintf("vTask2 complete, deleting task\r\n");
  vTaskDelete(NULL);
  
  
}

int main() {
  sciInit();
  spiInit();

  initSciPrint();
  initSpiMutex();

  sciPrintf("Starting Sun Position Tests\r\n");

  //xTaskCreateStatic(vTask1, "SunPositionTests", 2560, NULL, 1, taskStack, &taskBuffer);

  xTaskCreateStatic(vTask2, "SunPositionTests2", 2560, NULL, 1, taskStack, &taskBuffer);

  vTaskStartScheduler();

  while (1)
    ;
}
